### ISSUE TITLE
jointsOrder and jointSet have different sizes 

### ISSUE THREAD

**Issue by davidpagnon** [KULeuvenNeuromechanics/PredSim#112]
When running main.py with Demo data I have used in Moco ([model](https://github.com/stanfordnmbl/opencap-processing/blob/main/Moco/models/LaiArnoldModified2017_contacts.osim) and [mot](https://github.com/stanfordnmbl/opencap-processing/blob/main/Moco/exampleWalking/walking1_videoAndMocap.mot) files), I get the following error in the log files before it even starts the optimization process:

```Traceback (most recent call last): 
  File "osimtocppexe.py", line 81, in <module> 
  File "utilities.py", line 548, in writeCppFile 
AssertionError: jointsOrder and jointSet have different sizes 
[77812] Failed to execute script 'osimtocppexe' due to unhandled exception! 
```

- Do you have any idea how to solve this?
- I would have liked to debug it myself, but I don't really know how python files are handled within Matlab. Changes to the Utilities.py file do not seem to take effect.

**Comment by davidpagnon** [comment]
So I investigated it a little more, and this issue happens when the model dll does not exist (osim2dll.m, line 39):
`~isfile(fullfile(S.misc.subject_path,S.misc.external_function))` 

I'm suprised jointsOrder and jointSet have different sizes, since:
- I defined jointsOrder in main.m: `S.Cpp2Dll.jointsOrder = {'ground_pelvis', 'hip_r','walker_knee_r','patellofemoral_r','ankle_r','subtalar_r','mtp_r','hip_l','walker_knee_l','patellofemoral_l','ankle_l','subtalar_l','mtp_l','back','acromial_r','elbow_r','radioulnar_r','radius_hand_r','acromial_l','elbow_l','radioulnar_l','radius_hand_l'};`
- And checking jointSet in Python OpenSim (`[j.getName() for j in inModel.getJointSet()]`) also gives the exact same strings.

Thanks in advance, any help would be much appreciated!

**Comment by Lars-DHondt-KUL** [comment]
Looks like your error occurred inside the [OpenSimAD submodule](https://github.com/Lars-DHondt-KUL/opensimAD/tree/144a09414a52ed4fa3c538580dc8d79ee5f56bfb). 

> When running main.py with Demo data I have used in Moco ([model](https://github.com/stanfordnmbl/opencap-processing/blob/main/Moco/models/LaiArnoldModified2017_contacts.osim) and [mot](https://github.com/stanfordnmbl/opencap-processing/blob/main/Moco/exampleWalking/walking1_videoAndMocap.mot) files), I get the following error in the log files before it even starts the optimization process:

A slightly adapted (and scaled) version of the model you use is [included as example with OpenSimAD](https://github.com/Lars-DHondt-KUL/opensimAD/tree/144a09414a52ed4fa3c538580dc8d79ee5f56bfb/examples), so you could start from that one.

[OpenSimAD cannot handle coupling constraints](https://github.com/Lars-DHondt-KUL/opensimAD/tree/144a09414a52ed4fa3c538580dc8d79ee5f56bfb#Limitations) for the inverse dynamics. Since that model uses those for the patellofemoral joint, that joint and the patella are ignore for the inverse dynamics.

> I defined jointsOrder in main.m: S.Cpp2Dll.jointsOrder = {'ground_pelvis', 'hip_r','walker_knee_r','patellofemoral_r','ankle_r','subtalar_r','mtp_r','hip_l','walker_knee_l','patellofemoral_l','ankle_l','subtalar_l','mtp_l','back','acromial_r','elbow_r','radioulnar_r','radius_hand_r','acromial_l','elbow_l','radioulnar_l','radius_hand_l'};

You could try:
- Also define `S.Cpp2Dll.coordinatesOrder`, and make sure that the order is consistent with the joint order.
- Leave out the patellofemoral joints and coordinates.

> I would have liked to debug it myself, but I don't really know how python files are handled within Matlab. Changes to the Utilities.py file do not seem to take effect.

Handling python files in matlab requires some extra work, so we use compiled python files. You can find them in the folder you selected for `S.Cpp2Dll.PathCpp2Dll_Exe`.
