### ISSUE TITLE
getBounds.m: Adjust bounds to be symmetric - Not relevant for full gait cycle

### ISSUE THREAD

**Issue by tombuurke** [KULeuvenNeuromechanics/PredSim#116]
**Describe the bug**
Lines 98-112 in getBounds.m should only apply to a half gait cycle, not full gait cycle.

**To Reproduce**
1. Which script did you run? getBounds.m
2. What settings did you use? master branch.
3. What kind of OpenSim model did you use? Link to generic model, attach specific model, or describe model (bodies, joints, coordinates) if it is confidential. N.A.

**Log file**
No log file

**Software versions**
N.A.

**Additional context**
Shouldn't be a huge issue for now, but something to clean up in the future.

**Comment by VDB-Bram** [comment]
Hi @tombuurke,

Can you share the permalink of lines of code you are referring to? To me it is not clear for which version of the file this bug is present.

e.g. `https://github.com/KULeuvenNeuromechanics/PredSim/blob/d294d85d61ca3249591f45e81f889893e30d4a08/OCP/getBounds.m#L98-L112` results in https://github.com/KULeuvenNeuromechanics/PredSim/blob/d294d85d61ca3249591f45e81f889893e30d4a08/OCP/getBounds.m#L98-L112
